<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vitrolles"
 *
 * Auto generated by Extension Builder 2016-01-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'reservation',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Piment Rouge',
	'author_email' => 'typo3@pimentrouge.fr',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '9.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);